name: Go Cross-Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.20]  # Specify your Go version
        os: [ubuntu-latest]
        arch: [armv7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.arch }}
        env:
          GOOS: linux
          GOARCH: arm
          GOARM: 7
        run: |
          go build -v -o go-mqttclient-armv7 main.go

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: go-mqttclient-armv7
          path: go-mqttclient-armv7

